---

# HOSTS
hosts:
  vars:
    become: true
    become_method: sudo
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    # LOCALHOST
    local:
      hosts:
        localhost:
          ansible_connection: local