---

- name: Run tcpdump on specified network port
  command: tcpdump -nn -v -i en4 -s 1500 -c 1 'ether[20:2] == 0x2000'
  register: tcpdump

- name: Set default set_fact variables
  set_fact:
    tcpdump_switch: "{{ tcpdump.stdout | regex_search('10.[0-9]+.[0-9]+.[0-9]+') }}"
    tcpdump_port: "{{ tcpdump.stdout | regex_search('GigabitEthernet+[0-9]+/[0-9]+/[0-9]+') }}"
    tcpdump_vlan: "{{ tcpdump.stdout | regex_search('bytes: [0-9]+') | regex_replace('bytes: ') }}"

- name: Print tcpdump relevant information
  no_log: false
  debug:
    msg:
      - "Switch IP: {{ tcpdump_switch }}"
      - "Port: {{ tcpdump_port }}"
      - "Vlan: {{ tcpdump_vlan }}"